name: Build and Deploy to OCP

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Echo secret length (sanitized check)
      run: |
        echo "Username length: ${#DOCKER_USERNAME}"
        echo "Token length: ${#DOCKER_PASSWORD}"
     
    - name: Docker Login (Debug Mode)
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        echo "Login exit code: $LASTEXITCODE"
      shell: powershell
    
      
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/simple-webapp-color:1.3 .

    - name: Push to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/simple-webapp-color:1.3

    - name: Install OpenShift CLI
      run: |
        curl -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz | tar -xz
        sudo mv oc kubectl /usr/local/bin/
        
    - name: Debug DNS
      run: nslookup https://api.crc.testing:6443
      
    - name: Login to OpenShift
      run: |
        oc login ${{ secrets.OCP_SERVER }} --token=${{ secrets.OCP_TOKEN }} --insecure-skip-tls-verify

    - name: Deploy to OpenShift
      run: |
        oc project ${{ secrets.OCP_NAMESPACE }}
        oc delete deployment simple-webapp-color || true
        oc run simple-webapp-color \
          --image=${{ secrets.DOCKER_USERNAME }}/simple-webapp-color:1.3 \
          --port=3000 \
          --restart=Always
        oc expose pod simple-webapp-color --port=3000 --name=simple-webapp-service || true
